### ISSUE TITLE
openprompt ERROR

### ISSUE THREAD

**Issue by YvoGao** [1KE-JI/HierVerb#3]
ERROR: Could not find a version that satisfies the requirement openprompt==0.1.2 (from versions: 0.1.1, 1.0.0, 1.0.1)
ERROR: No matching distribution found for openprompt==0.1.2
I try to install openprompt other versions, but they do not work,  

they all say
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    import openprompt
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/openprompt/__init__.py", line 4, in <module>
    from .trainer import ClassificationRunner, GenerationRunner
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/openprompt/trainer.py", line 9, in <module>
    from tensorboardX import SummaryWriter
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .writer import SummaryWriter
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .comet_utils import CometLogger
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .summary import _clean_tag
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .proto.summary_pb2 import Summary
  File "/data/gaoyunlong/anaconda3/envs/HV/lib/python3.6/site-packages/tensorboardX/proto/summary_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder'

**Comment by YvoGao** [comment]
fix
